# Generated by Django 4.1.7 on 2023-04-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='user',
            new_name='User',
        ),
        migrations.AddField(
            model_name='userrole',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.role'),
        ),
    ]
