# Generated by Django 4.1.7 on 2023-04-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_rename_user_userrole_user_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.role'),
        ),
    ]
