# Generated by Django 4.1.7 on 2023-04-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapterNumber', models.IntegerField()),
                ('ChapterName', models.CharField(max_length=225)),
                ('ContentStory', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StroryName', models.CharField(max_length=225)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.chapter')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='Story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.story'),
        ),
        migrations.CreateModel(
            name='CategoryStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.category')),
                ('Story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.story')),
            ],
        ),
    ]
