# Generated by Django 4.1.7 on 2023-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_category_chapter_story_history_chapter_story_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='StroryName',
            new_name='StoryName',
        ),
        migrations.AddField(
            model_name='story',
            name='Author',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='CoverImage',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='Soure',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='Status',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
