# Generated by Django 4.1.7 on 2023-04-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_rename_stroryname_story_storyname_story_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='Soure',
            new_name='Source',
        ),
    ]
