# Generated by Django 4.1.7 on 2023-04-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0008_rename_soure_story_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.user'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='Story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='Entity.story'),
        ),
    ]
