# Generated by Django 4.1.7 on 2023-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0009_story_user_alter_chapter_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ContentStory',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='story',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
