# Generated by Django 4.1.7 on 2023-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0010_alter_chapter_contentstory_alter_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Check',
            field=models.IntegerField(null=True),
        ),
    ]
