# Generated by Django 4.1.7 on 2023-04-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0011_story_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='DayBrowser',
            field=models.DateTimeField(null=True),
        ),
    ]
