# Generated by Django 4.1.7 on 2023-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0013_chapter_dayupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
    ]
