# Generated by Django 4.1.7 on 2023-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0014_history_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
